# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created: Sun Mar 22 14:18:14 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(301, 682)
        Form.setMinimumSize(QtCore.QSize(299, 682))
        self.listView = QtGui.QListView(Form)
        self.listView.setGeometry(QtCore.QRect(0, 5, 301, 671))
        self.listView.setObjectName(_fromUtf8("listView"))
        self.springLayout = QtGui.QPushButton(Form)
        self.springLayout.setGeometry(QtCore.QRect(5, 260, 121, 32))
        self.springLayout.setObjectName(_fromUtf8("springLayout"))
        self.Thickness = QtGui.QSlider(Form)
        self.Thickness.setGeometry(QtCore.QRect(130, 110, 156, 22))
        self.Thickness.setTracking(False)
        self.Thickness.setOrientation(QtCore.Qt.Horizontal)
        self.Thickness.setObjectName(_fromUtf8("Thickness"))
        self.snapshot = QtGui.QPushButton(Form)
        self.snapshot.setGeometry(QtCore.QRect(0, 610, 141, 32))
        self.snapshot.setObjectName(_fromUtf8("snapshot"))
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(5, 140, 111, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.Quit = QtGui.QPushButton(Form)
        self.Quit.setGeometry(QtCore.QRect(156, 640, 141, 32))
        self.Quit.setObjectName(_fromUtf8("Quit"))
        self.scroll = QtGui.QScrollArea(Form)
        self.scroll.setGeometry(QtCore.QRect(10, 310, 281, 291))
        self.scroll.setWidgetResizable(True)
        self.scroll.setObjectName(_fromUtf8("scroll"))
        self.scrollWidgetContents_11 = QtGui.QWidget()
        self.scrollWidgetContents_11.setGeometry(QtCore.QRect(0, 0, 279, 289))
        self.scrollWidgetContents_11.setObjectName(_fromUtf8("scrollWidgetContents_11"))
        self.BrainList = QtGui.QListView(self.scrollWidgetContents_11)
        self.BrainList.setGeometry(QtCore.QRect(0, 0, 281, 291))
        self.BrainList.setObjectName(_fromUtf8("BrainList"))
        self.scroll.setWidget(self.scrollWidgetContents_11)
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(5, 20, 121, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(5, 110, 111, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.Layout = QtGui.QComboBox(Form)
        self.Layout.setGeometry(QtCore.QRect(130, 75, 161, 26))
        self.Layout.setObjectName(_fromUtf8("Layout"))
        self.Layout.addItem(_fromUtf8(""))
        self.Layout.addItem(_fromUtf8(""))
        self.Layout.addItem(_fromUtf8(""))
        self.Layout.addItem(_fromUtf8(""))
        self.Layout.addItem(_fromUtf8(""))
        self.Layout.addItem(_fromUtf8(""))
        self.Layout.addItem(_fromUtf8(""))
        self.Layout.addItem(_fromUtf8(""))
        self.Layout.addItem(_fromUtf8(""))
        self.getSnapshots = QtGui.QPushButton(Form)
        self.getSnapshots.setGeometry(QtCore.QRect(156, 610, 141, 32))
        self.getSnapshots.setObjectName(_fromUtf8("getSnapshots"))
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(5, 80, 59, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.highlightEdges = QtGui.QCheckBox(Form)
        self.highlightEdges.setGeometry(QtCore.QRect(10, 235, 131, 20))
        self.highlightEdges.setChecked(True)
        self.highlightEdges.setObjectName(_fromUtf8("highlightEdges"))
        self.Regions = QtGui.QLabel(Form)
        self.Regions.setGeometry(QtCore.QRect(5, 290, 91, 16))
        self.Regions.setObjectName(_fromUtf8("Regions"))
        self.dataset = QtGui.QPushButton(Form)
        self.dataset.setGeometry(QtCore.QRect(0, 640, 141, 32))
        self.dataset.setObjectName(_fromUtf8("dataset"))
        self.colorEdges = QtGui.QCheckBox(Form)
        self.colorEdges.setGeometry(QtCore.QRect(150, 160, 131, 20))
        self.colorEdges.setChecked(True)
        self.colorEdges.setObjectName(_fromUtf8("colorEdges"))
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(5, 50, 71, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.preservePositions = QtGui.QCheckBox(Form)
        self.preservePositions.setGeometry(QtCore.QRect(10, 160, 141, 20))
        self.preservePositions.setChecked(True)
        self.preservePositions.setObjectName(_fromUtf8("preservePositions"))
        self.hover = QtGui.QCheckBox(Form)
        self.hover.setGeometry(QtCore.QRect(10, 190, 111, 20))
        self.hover.setChecked(True)
        self.hover.setObjectName(_fromUtf8("hover"))
        self.transparent = QtGui.QCheckBox(Form)
        self.transparent.setGeometry(QtCore.QRect(150, 190, 141, 20))
        self.transparent.setChecked(True)
        self.transparent.setObjectName(_fromUtf8("transparent"))
        self.correlation = QtGui.QComboBox(Form)
        self.correlation.setGeometry(QtCore.QRect(130, 15, 161, 26))
        self.correlation.setObjectName(_fromUtf8("correlation"))
        self.correlation.addItem(_fromUtf8(""))
        self.correlation.addItem(_fromUtf8(""))
        self.NodeSize = QtGui.QComboBox(Form)
        self.NodeSize.setGeometry(QtCore.QRect(130, 45, 161, 26))
        self.NodeSize.setObjectName(_fromUtf8("NodeSize"))
        self.NodeSize.addItem(_fromUtf8(""))
        self.NodeSize.addItem(_fromUtf8(""))
        self.NodeSize.addItem(_fromUtf8(""))
        self.NodeSize.addItem(_fromUtf8(""))
        self.NodeSize.addItem(_fromUtf8(""))

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.springLayout.setText(_translate("Form", "Spring Layout", None))
        self.snapshot.setText(_translate("Form", "Capture Snapshot ", None))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Edge orientation:</span></p></body></html>", None))
        self.Quit.setText(_translate("Form", "Close", None))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Application mode:</span></p></body></html>", None))
        self.label_5.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Edge Thickness: </span></p></body></html>", None))
        self.Layout.setItemText(0, _translate("Form", "sfdp", None))
        self.Layout.setItemText(1, _translate("Form", "twopi", None))
        self.Layout.setItemText(2, _translate("Form", "fdp", None))
        self.Layout.setItemText(3, _translate("Form", "circo", None))
        self.Layout.setItemText(4, _translate("Form", "circular", None))
        self.Layout.setItemText(5, _translate("Form", "spring", None))
        self.Layout.setItemText(6, _translate("Form", "random", None))
        self.Layout.setItemText(7, _translate("Form", "shell", None))
        self.Layout.setItemText(8, _translate("Form", "neato", None))
        self.getSnapshots.setText(_translate("Form", "Retrieve Snapshot", None))
        self.label_3.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Layout: </span></p></body></html>", None))
        self.highlightEdges.setText(_translate("Form", "Highlight edges", None))
        self.Regions.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Brain regions:</span></p></body></html>", None))
        self.dataset.setText(_translate("Form", "Load Datasets", None))
        self.colorEdges.setText(_translate("Form", "Only edges", None))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-weight:600;\">Node size:</span></p></body></html>", None))
        self.preservePositions.setText(_translate("Form", "Preserve positons", None))
        self.hover.setText(_translate("Form", "Hover Events", None))
        self.transparent.setText(_translate("Form", "Transparent nodes", None))
        self.correlation.setItemText(0, _translate("Form", "Correlation Strength", None))
        self.correlation.setItemText(1, _translate("Form", "Communities", None))
        self.NodeSize.setItemText(0, _translate("Form", "Centrality", None))
        self.NodeSize.setItemText(1, _translate("Form", "Betweeness", None))
        self.NodeSize.setItemText(2, _translate("Form", "ClosenessCentrality", None))
        self.NodeSize.setItemText(3, _translate("Form", "ParticipationCoefficient", None))
        self.NodeSize.setItemText(4, _translate("Form", "LoadCentrality", None))

